spring:
    profile:
        active:
        - dev
---
spring:
    profile: dev
    application: 
        name: microservice-config-atguigu-dev
---            
spring:
    profile: test
    application: 
        name: microservice-config-atguigu-test